global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: true

entryPoints:
  api:
    address: :3000

providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`localhost`)"
